### ISSUE TITLE
-o does not work as advertised

### ISSUE THREAD

**Issue by marcvs** [indigo-dc/oidc-agent#215]
```
$ oidc-token -o iam 
```
only gives me the token:
```
eyJra...................b0
```
--help says it would output 
```
OIDC_AT=eyJra......bo
```

also: -o=asdf returns:
```
=asdf-eyJra.......bo
```

**Comment by zachmann** [comment]
> ```
> $ oidc-token -o iam 
> ```
> 
> only gives me the token:
> 
> ```
> eyJra...................b0
> ```

This is working as intended.

> --help says it would output
> 
> ```
> OIDC_AT=eyJra......bo
> ```

No from the help:
```
If neither -i nor -e is set and OIDC_AT is not passed, the token is printed to stdout (Same behaviour as without this option).
```
So when only providing `-o` this will only print the token to stdout (as without the option). You hvae to specify the env var name (or additionally use `-i` or `-e`

> also: -o=asdf returns:
> 
> ```
> =asdf-eyJra.......bo
> ```
This is also correct behavior. Your syntax is wrong. The `=` is only used with the long option. So you can use one of the following so that the env var `asdf` is used:
```
oidc-token -oasdf
oidc-token --token=asdf
```
