### ISSUE TITLE
Python client does not seem to work

### ISSUE THREAD

**Issue by paulmillar** [indigo-dc/oidc-agent#257]
Following the instructions: install `liboidcagent` python library and use the `get_access_token` function, but I get an error when attempting to get a token from my `XDC` account.

```
paul@sprocket:~$ pip3 install liboidcagent
Collecting liboidcagent
  Using cached https://files.pythonhosted.org/packages/cb/4e/c3a5acd732610e63da1cc1cfabb2dbfd06f45cb4e4b0215ef85c5c85eb4a/liboidcagent-0.2.0-py3-none-any.whl
Installing collected packages: liboidcagent
Successfully installed liboidcagent-0.2.0
paul@sprocket:~$ python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import liboidcagent as agent
>>> agent.get_access_token("XDC")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'liboidcagent' has no attribute 'get_access_token'
>>> 
```

The error suggests the library is badly deployed or just broken.

**Comment by zachmann** [comment]
You're right, something seems to be broken. `liboidcagent 0.1.5` is last version that works currectly. I'll investigate and work on a fix.
Since this is a problem of the python library (or just the packaging) but not `oidc-agent` I close this issue and open a new one on [`liboidc-agent-py`](https://github.com/indigo-dc/liboidc-agent-py)

**Comment by zachmann** [comment]
The issue has been fixed.
