### ISSUE TITLE
Add ability to force oidc-agent to refresh a token

### ISSUE THREAD

**Issue by paulmillar** [indigo-dc/oidc-agent#260]
Under normal circumstances, oidc-agent works fine and correctly caches the access token (AT), automatically obtaining a fresh AT when necessary.  However, life isn't always normal.  If there's a problem with the OP then the cached AT may be rejected by the OP, although the AT hasn't expired yet.

Such problems should be fixed in the OP; however, it would still be potentially helpful to have a mechanism where the user can force oidc-agent to discard the cached AT and obtain a fresh token.

Such a feature should (probably) be included with "experts only" warnings, saying this feature shouldn't be used for day-to-day operations.

**Comment by zachmann** [comment]
The `-t` option can be used to specify how long the token should be valid. This mechanism can be used to force a new token, if the provided time is greater than the time the current token is still valid a new token will be returned (and cached). Usually `oidc-token -t3600` should be enough, but if tokens are longer lived a higher value must be used.

Neverthess, such an option could be implemented. But since there is a easy way to do this, I don't know if it is necessary.

**Comment by marcvs** [comment]
Apparently -t is not so obvious, and maybe I want a new token that lives only 50 seconds?

**Comment by zachmann** [comment]
The spec does not provide a way to request AT at the provider with a certain lifetime. So if you want a new token it will be valid for the time the provider says, e.g. 1h

**Comment by paulmillar** [comment]
As much as it's convenient (in this case) that oidc-agent behaves this way, it's actually a surprise.

I had just assumed that oidc-token would return an error, if the new token's validity wasn't as long as the duration requested by the user.

With the current semantics, I would have to somehow check the validity of the token to know that the token is valid for long enough (e.g., use the user-info endpoint).

**Comment by paulmillar** [comment]
@marcvs I had a similar goal. I wanted to test how software reacted to tokens expiring, so wanted a short-lived token.  To do this, I registered oidc-agent again (i.e., as a new client) and Andrea did some voodoo configuration in IAM to restrict the lifetime of tokens for this client.

**Comment by zachmann** [comment]
> As much as it's convenient (in this case) that oidc-agent behaves this way, it's actually a surprise.
> 
> I had just assumed that oidc-token would return an error, if the new token's validity wasn't as long as the duration requested by the user.
In the general case this is not possible, since the `expires_in` claim is optional, so oidc-agent does not know how long the token is actually valid. But in this case the token cannot really be cached. I might have to think about this. We could give a warning that the token might be not valid as long as specified.
> With the current semantics, I would have to somehow check the validity of the token to know that the token is valid for long enough (e.g., use the user-info endpoint).
The guarntee we give is that the token will be valid for the specified time, if this time is below the lifetime of ATs for the provider / client. 
Of course if the lifetime for a provider is 1h and a user requests a lifetime of 2h this is impossible for oidc-agent to fulfill and it just returns a token valid for 1h. But as mentioned in this case we might want to give a warning.

**Comment by marcvs** [comment]
To enable people to easier find that feature, adding a short and a long option like "--new-at" or "--refresh" to oidc-token could help.
