### ISSUE TITLE
Clarify use of public clients

### ISSUE THREAD

**Issue by andreaceccanti** [indigo-dc/oidc-agent#283]
Hello Gabriel,

I have troubles understanding oidc-agent support for public clients.
I tried to have a public client configured locally but failed badly in  doing so.

As you know, for a public client there's no client secret that needs to be protected. Also typically public clients are not allowed the 'offline_access' scope, so no refresh tokens. Also, the public client is already registered in the provider,
all I need to know on the client side is the client_id, issuer URI and allowed scopes.

How can I configure oidc-agent so that:

- I can provide a list of public clients for an host that can be used by people. I have read in the doc about this `/etc/oidc-agent/pubclients.config`, but what is the format of such config file?
- I can get an access token out a token issuer using a public client ?

Thanks in advance for your help!
Andrea

**Comment by zachmann** [comment]
Hi Andrea,

> Also typically public clients are not allowed the 'offline_access' scope, so no refresh tokens. 

For normal usage of oidc-agent this is a problem. Since the basic conecpt of oidc-agent is to obtain a refresh token through one of the oidc flows in oidc-gen and after that only using the refresh flow it is essential for oidc-agent to have an refresh token.

> How can I configure oidc-agent so that:
> - I can provide a list of public clients for an host that can be used by people. I have read in the doc about this /etc/oidc-agent/pubclients.config, but what is the format of such config file?

You're right the `/etc/oidc-agent/pubclient.config` is used for providing public client "credentials". If you installed oidc-agent from package then there already should be several entries. 
There should be one entry per line and each entry has the format: `<client_id>[:<client_secret>]@<issuer_url>`
The part with the client secret is optional since some provider do issue a client secret to public clients and some don't. In version 4.0.0 the format will be extended to also include the scopes that are available for the registered public client.

If a public client is listed there it can be easily used by `oidc-gen`. By calling `oidc-gen --pub` the public client for the used issuer will be used. (oidc-gen expects that there is only one entry per issuer). The public client will also be used when `oidc-gen` without the `--pub` option, but dynamic client registration is not supported.

There is also another way to use a public client, without modifying the `pubclient.config` file. One can provide the client credentials to `oidc-gen` in the manual mode `-m`. If the public client does not have a client secret one also has to pass the `--pub` option.

> - I can get an access token out a token issuer using a public client ?

If you have finished the oidc-gen flow and created an account config file, you can use it just as any other account config, i.e. `oidc-token <shortname>` gives an access token.
There's currently no other way to obtain an access token without creating the account config file.

I hope this answer clarifies things.

**Comment by andreaceccanti** [comment]
Hello Gabriel,

> > Also typically public clients are not allowed the 'offline_access' scope, so no refresh tokens.
> 
> For normal usage of oidc-agent this is a problem. Since the basic conecpt of oidc-agent is to obtain a refresh token through one of the oidc flows in oidc-gen and after that only using the refresh flow it is essential for oidc-agent to have an refresh token.
> 

Ah, but basically (as you know from an offline email exchange) what we need is not to create a local account for a user,
but just the ability to use oidc-agent to get an access token that will then be used for the registraton of a client.

> > How can I configure oidc-agent so that:
> > 
> > * I can provide a list of public clients for an host that can be used by people. I have read in the doc about this /etc/oidc-agent/pubclients.config, but what is the format of such config file?
> 
> You're right the `/etc/oidc-agent/pubclient.config` is used for providing public client "credentials". If you installed oidc-agent from package then there already should be several entries.

Ouch, not on MacOS. I will check the format on a CENTOS 7 installation, thanks for this hint.
I think it would be good to explain the file format in the docs.

> There should be one entry per line and each entry has the format: `<client_id>[:<client_secret>]@<issuer_url>`
> The part with the client secret is optional since some provider do issue a client secret to public clients and some don't. In version 4.0.0 the format will be extended to also include the scopes that are available for the registered public client.
> 

> If a public client is listed there it can be easily used by `oidc-gen`. By calling `oidc-gen --pub` the public client for the used issuer will be used. (oidc-gen expects that there is only one entry per issuer). The public client will also be used when `oidc-gen` without the `--pub` option, but dynamic client registration is not supported.

But this requires that the public client has access to the `offline_access` scope, right?

Thanks for your help!

**Comment by zachmann** [comment]
> Ah, but basically (as you know from an offline email exchange) what we need is not to create a local account for a user,
> but just the ability to use oidc-agent to get an access token that will then be used for the registraton of a client.

Yes, I opened a new issue for that #287 

> > You're right the `/etc/oidc-agent/pubclient.config` is used for providing public client "credentials". If you installed oidc-agent from package then there already should be several entries.
> 
> Ouch, not on MacOS. I will check the format on a CENTOS 7 installation, thanks for this hint.

For rpm it should be fine. On MacOS I cannot check everything reliable. But I will look into it when I do the check for v4.0.0

> I think it would be good to explain the file format in the docs.

You're right. I added it to the list #286 

> > If a public client is listed there it can be easily used by `oidc-gen`. By calling `oidc-gen --pub` the public client for the used issuer will be used. (oidc-gen expects that there is only one entry per issuer). The public client will also be used when `oidc-gen` without the `--pub` option, but dynamic client registration is not supported.
> 
> But this requires that the public client has access to the `offline_access` scope, right?

Currently oidc-agent requires all clients to have the `offline_access` scope, yes. With the new option this will not be required (but only there).
