### ISSUE TITLE
Expired refresh token: user guidance

### ISSUE THREAD

**Issue by marcvs** [indigo-dc/oidc-agent#327]
If a refresh token is expired (e.g. when `oidc-token` is run) it would be very useful to display to the user which actions probably make sense.  
For example: oidc-gen --reauthenticate <configname>

**Comment by nulltrope** [comment]
while I agree with this, I would take it a step further and suggest that `oidc-token` automatically re-run `oidc-gen --reauthenticate` when it detects a refresh token is expired, or at the very least have an option in the client configuration like `autoReauthenticate` to enable this behavior

**Comment by zachmann** [comment]
I don't really agree, but I'm open to discuss it.
From my experience refresh token are usually really long lived and often do not expire at all, so it is rather unlikely that one has to reauthenticate because the RT expired. Revocation should be even less often.
However, if one uses an OP where RT are relatively short-lived, e.g. 10days, than I understand that an auto feature is useful.

What we have to consider is that, reauthentication requires true user interaction:
- Usually the encryption password is needed to store the new RT, however there are also setups where this is not needed (e.g. password saved in the agent)
- The reauthentication at the OP will always require the user to be present.

Calls to oidc-token - or more generally AT requests for the agent - on the other hand can work without user interaction. In such a case (let's say there is a script requesting an AT), the script will hang until the user is present, completes the oidc flow, the agent stores the new RT and returns the AT to the script. Without the auto reauthentication the script will just get an error and might be able to handle it.

Also if the user is not present when the reauthentication flow is started, the flow can timeout, so that the user has to restart it again when he comes back.

So the point here is, that when we notice that the RT is not valid anymore, we don't know if the user is actually present, so I think it is better to present him with instructions than to start the flow.

**Comment by nulltrope** [comment]
@zachmann I guess it depends on your identity provider / issuer, but at least with Keycloak even the refresh tokens tend to be short lived, unless of course you are talking about offline tokens which can be weeks or months.

You make a good point about not requiring user interaction for AT requests for the agent- I hadn't thought of that but it makes sense. I suppose if a script wanted to be really smart about it, it could just catch this specific error and run oidc-gen itself (and wait for user input).

I agree that a reasonable improvement would be to just print instructions for re-authenticating in the case that an access token has expired.

**Comment by zachmann** [comment]
> @zachmann I guess it depends on your identity provider / issuer, but at least with Keycloak even the refresh tokens tend to be short lived, unless of course you are talking about offline tokens which can be weeks or months.

Yes this depends on the provider. Generally, we assume long lived refresh tokens; a high refresh token lifetime is essential for users not having to reauthenticate frequently.
Usually refresh tokens are long lived and only returned if a client requestes it through the `offline_access` scope. Keycloak seems to be kind of special in that regard. (Of course this depends on the configuration, but) keycloak returns a short-lived refresh token when requesting an AT even if no RT was requested; and on request returns a longer-lived offline RT. 
This longer-lived RT is what we want to use with oidc-agent. oidc-agent always uses the `offline_access` scope to request a (long-lived) RT.

> You make a good point about not requiring user interaction for AT requests for the agent- I hadn't thought of that but it makes sense. I suppose if a script wanted to be really smart about it, it could just catch this specific error and run oidc-gen itself (and wait for user input).

Yes, I was going to suggest this (but then forgot about it). If you really want to have the auto-requthentication behavior, you can write a simple wrapper around `oidc-token` that checks for the error and then calls oidc-gen.

> I agree that a reasonable improvement would be to just print instructions for re-authenticating in the case that an access token has expired.

Yes, we'll add these.

**Comment by zachmann** [comment]
Added to `liboidc-agent` and `oidc-token` in 4.2.0
```
$ ./bin/oidc-token google-fake 
Error: invalid_grant: Bad Request
Properly the refresh token expired. To create a new one, just run:
	$ oidc-gen google-fake --reauthenticate
```

**Comment by zachmann** [comment]
So I gave it some more thoughts.

You're right we could implement it in a similar way as the already existing auto-load feature and rely on the gui prompting for displaying the url to the user.

However, there are some things to be considered:
- Actually we cannot guarantee that the solution we propose is the correct one, e.g. when we get an `invalid_grant` error, it is most likely an expired RT but theoretically could also be something else.
- At this point we don't know which oidc flow we should use, we could do an educated guess, but it might be wrong. But I have an idea for a good solution.
- We absolutely require the gui prompting to be available (which is fine, this is also required for autoload accounts)

**Comment by zachmann** [comment]
Moving discussion about the auto reauthentication to #339
