### ISSUE TITLE
oidc-gen --issuer flag not accepting argument

### ISSUE THREAD

**Issue by nulltrope** [indigo-dc/oidc-agent#336]
Running `oidc-gen` with the `--issuer` flag does not seem to accept any arguments to supply the issuer URL
```
oidc-gen --manual --issuer=https://example.com
oidc-gen: option `--issuer' doesn't allow an argument
Try `oidc-gen --help' or `oidc-gen --usage' for more information.
```

I also tried without the `=` but then the issuer flag does not seem to be used at all

I am using oidc-agent 4.1.1 on Mac OS 10.15.7

**Comment by zachmann** [comment]
I cannot reproduce it on debian.
Can you please try `--iss` instead of `--issuer`?
Can you also please check if the error also occurs for the other options, such as `--scope`, `--port`, `--client-id`.

**Comment by nulltrope** [comment]
Interestingly, it does work with `--iss` flag, but not `--issuer`. The error does not occur for other flags that I have seen

**Comment by zachmann** [comment]
Sorry for the delayed response. I actually wrote it earlier, but forgot to actually send it. 🤦🏿 

As I already suspected it seems to be related to the fact that this option (`--issuer`) is an alias (to `--iss`).
However, I don't know exactly what the problem is there.

It would be super helpful if you could test the following:
- Clone the repo (`git clone https://github.com/indigo-dc/oidc-agent`)
- `cd` into the cloned repo
- Edit the file `src/oidc-gen/oidc-gen_options.c`
  - In line 94 substitute the `0` with `"ISSUER_URL"`
- Build the project with `make` (Since, you installed with homebrew you already should have all the needed dependencies available)
- Test the `--issuer` option of the new binary: `./bin/oidc-gen --issuer=....`

**Comment by nulltrope** [comment]
Just made your suggested change locally and confirmed it fixes the issue

```
./bin/oidc-gen --pub --client-id=<redacted> --client-secret="" --scope="openid" --issuer=<redacted> --port=4242 test
No account exists with this short name. Creating new configuration ...
Generating account configuration ...
```

**Comment by zachmann** [comment]
Ok, thanks for the confirmation. I'll fix it.
