### ISSUE TITLE
Inconsistency in command-line options between `oidc-gen` and `oidc-token`

### ISSUE THREAD

**Issue by paulmillar** [indigo-dc/oidc-agent#357]
The `oidc-gen` man page says:

```
--scope=SCOPE
          Set SCOPE as the scope to be used. SCOPE can be a space separated list of multiple values. Use
          'max' to  use  all available scopes for this provider.
```

while the `oidc-token` man page says:

```
-s, --scope=SCOPE
       Scope to be requested for the requested access token. To provide multiple scopes, use this option
       multiple times.
```

I think it would be a good idea if `oidc-gen` and `oidc-token` used a consistent approach in how the user specifies the desired scopes.

**Comment by zachmann** [comment]
You're right, there's certainly some inconsistency.
Some background information where this comes from:
- Speciifying the `-s` option multiple times was added to `oidc-token`
- `oidc-gen` started with interactive prompting only; there it is more natural to use a single prompt with space separated values
- Later the command line options were added to `oidc-gen` and we copied the behavior from the interactive prompting

So one can say the inconsistency between `oidc-token` and `oidc-gen` comes from the consistency within `oidc-gen`.

I see different "solutions":
- Leaving it as it is (but having inconsistency)
- Adapting the `oidc-gen` command line option (having a minor inconsistency within `oidc-gen`, however since command line options and prompting are different concepts, I think this is fine)
- Adapting `oidc-token` to use a space-separated list.

I think the second option will be the best, especially since changing `oidc-token` as supposed in the last solution will have greater impact on other software that then has to adapt.

@marcvs what do you think?

**Comment by paulmillar** [comment]
Thanks for the explanation @zachmann --- I guessed it was something like that ;-)

I don't have a strong opinion which way to go: please choose whichever solution you like the best!

Also, that (for me) this is a low-priority issue.  I think it would be good to fix, but it's certainly not a burning issue.

I agree that modifying the semantics of `oidc-gen` is likely the least disruptive solution.

One last thing: there's yet another possibility: both oidc-gen and oidc-token could accept multiple `-s` options, but each value may contain a space-separated list of arguments.  For example, with these semantics, the following four command lines are equivalent:

    oidc-token -s foo -s bar -s baz PROVIDER
    oidc-token -s "foo bar" -s baz  PROVIDER
    oidc-token -s foo -s "bar baz"  PROVIDER
    oidc-token -s "foo bar baz" PROVIDER

On the positive, this would be compatible with existing usage, both for `oidc-gen` and `oidc-token`; however, it makes documenting the behaviour somewhat harder.

(I'm not advocating this approach, just pointing out it's an option -- please choose whichever you like the best!)

HTH,
Paul.

**Comment by marcvs** [comment]
Yep, I like Pauls suggestion. If `oidc-token` allowed both syntaxes (and `oidc-gen` too) it be the cleanest.
Maybe it is even enough to only to that for `oidc-token`, but I'm sure at some point, somebody will ask for `oidc-gen` to support the same thing :)

**Comment by zachmann** [comment]
I think it is not unlikely that person would be you @marcvs ;)
