### ISSUE TITLE
oidc-agent blocks on automatic re-authentication

### ISSUE THREAD

**Issue by paulmillar** [indigo-dc/oidc-agent#394]
Because of the problem described in #393, I was forced to kill the `yad` command.  I used SIGTERM (the default) to kill `yad`.

Killing `yad` had the expected knock-on effect of killing the the `oidc-prompt` command.

However, the spawned `oidc-agent` process did not seem to notice that the oidc-prompt process had terminated.  Consequently, it remained remained active.

Also, the original `oidc-token` command that triggered the prompt did not return.  My guess is that this is probably as a result of the dangling `oidc-agent` process.

Eventually, the `oidc-token` command does exit with the following output:
```
Error: No or malformed refresh token
Most likely the refresh token expired. To create a new one, just run:
        $ oidc-gen EGI-CheckIn --reauthenticate
```

This looks like a timeout in `oidc-token`, rather than an expected code-path.

HTH,
Paul.

**Comment by zachmann** [comment]
> This looks like a timeout in `oidc-token`, rather than an expected code-path.

There isn't a timeout in `oidc-token`. `oidc-token` will wait forever for a response from the agent. However, there is a timeout in the agent in waiting for a response from `oidc-prompt`.

But you are right that it would much better if the agent notices that `oidc-prompt` is killed. I'll have to check why this isn't the case.

**Comment by zachmann** [comment]
Usually the agent notices when `oidc-prompt` exists. However, the case you described is where the agent finds an expired refresh token and automatically triggers an re-authentication. This is a more complex scenario.

In this case the agent waits for the reauthentication to be finished (in your case that wasn't possible because the instructions in the prompt weren't available). Until that happens the agent does not accept other requests. Also the `oidc-token` didn't return because it was still waiting for a response from the agent (which was waiting for the re-authentication).
There is a timeout (5min) so the agent will eventually go back to normal operation and oidc-token received the (error) response as you described.

I understand that the blocking in the case of a pending re-authentication is sub-optimal (especially if the user closed the prompt window with the instructions),  but we don't have a better solution for this.
