### ISSUE TITLE
Support musl libc

### ISSUE THREAD

**Issue by mkszuba** [indigo-dc/oidc-agent#397]
It would be nice if oidc-agent could be built against musl, as it would make it easier to include it in low-footprint and/or embedded systems. My own experiments suggest only three, fairly minor, changes are required to make version 4.2.6 build, test and install without errors on a musl-based Linux system:

1. musl does not include the argp library so all tools using argp functionality should be linked against argp-standalone (https://github.com/ericonr/argp-standalone), which requires adding `-largp` to LFLAGS. This has to be done conditionally because glibc does not provide libargp;

2. oidc-agent uses several GNU extensions to the C standard library (_e.g._ extended signal-handling API in the `oidc-agent` prompt code) yet musl defaults to BSD compatibility. Trivial to fix, just add -D_GNU_SOURCE to CFLAGS - unconditionally this time, see below;

3. `oidc-gen` uses the internal glibc type `__sighandler_t`. Just use `sighandler_t` instead, that one works with both musl and glibc if _GNU_SOURCE is set.

**Comment by zachmann** [comment]
Hi Marek,

thanks for your request, of course we are interested in seeing oidc-agent getting widely used.

I started the work on this issue:
1. I added an option to include the `-largp` flag. However, I don't know how we could detect the need automatically; so at the moment it is only included if `USE_ARGP_SO` is set to 1, i.e. when calling `make USE_ARGP_SO=1`
2. I set `_GNU_SOURCE` in the `agent_prompt.c` file for the signal handling. Please let me know if other files need adaption.
3. I changed that and set `_GNU_SOURCE`.

You can find the changes in the [dev_4.3.0](https://github.com/indigo-dc/oidc-agent/tree/dev_4.3.0) branch. Please check if this is already enough or other modifications are needed.

Cheers,
Gabriel

**Comment by zachmann** [comment]
@mkszuba  If you have some spare time, it would be great if you could check again that the dev_4.3.0 branch builds as expected.

There were major changes to the `oidc-prompt` tool. (Which might not find too much usage with musl libc systems, but anyway would be great to verify that it works), which now is a C/C++ application instead of a bash script. On Linux it depends on gtk3 and gtk-webkit2 (debian packages are `ligbtk-3-0` and `libwebkit2gtk-4.0-37` + `libwebkit2gtk-4.0-dev` for building).
