### ISSUE TITLE
Update on-disk refresh token if OP issues a new RT. 

### ISSUE THREAD

**Issue by paulmillar** [indigo-dc/oidc-agent#406]
[Section 6](https://datatracker.ietf.org/doc/html/rfc6749#section-6) of  RFC 6749 OAuth spec says that
> The authorization server MAY issue a new refresh token, in which case
   the client MUST discard the old refresh token and replace it with the
   new refresh token. 

If the OP issues a new RT then oidc-agent will update the in-memory representation, but does not update the on-disk (stored) RT.

This causes problems when the oidc-agent losses the in-memory RT and (re)loads it from disk.  For example, in desktop environment this happens when the user next logs back in.

**Comment by paulmillar** [comment]
Just as possible inspiration, some possible solutions:

1. the agent could prompt the user to enter the password if the OP issues a new RT.  It uses the password to store the updated RT.
2. the agent could store the password (in addition to the RT) and update the on-disk RT automatically.
3. the stored information is updated to include an additional password (protected by the main password).  The agent could store the updated RT on disk (in a separate file) using this additional password.  When loading an RT, the agent checks to see if there's a new RT available (in the separate file).  If there is, it uses that RT and updates the on-disk storage.  It could also creates a new RT-update password -- this isn't needed, but might be a good idea.

Solution 1. is, perhaps, the easiest, but only works for scenarios where the user is present.

Solution 2. would involve storing the password in-memory.  This might be OK, as the RT (the thing protected by the password) is also stored in-memory.

Solution 3. would (perhaps) be the best approach, but requires the most work.

**Comment by zachmann** [comment]
You are right that this is a relevant point. This was also a topic on the wlcg authz mailing list a week ago.

As you noticed oidc-agent can handle a changing refresh token, but the challenging part is to store it back on disk, since the configuration is encrypted.

However, there are different solutions already implemented (including your suggested 1 and partly 2):
1. As you suggested the agent can prompt the user for the encryption password. This is automatically done (if the encryption password cannot be obtained through some other way, see below) if the `oidc-prompt` utility is installed. If this did not work for you, we have to look into it. This is the easiest solution and kind of serves as a backup, but as you noted it requires the user to be present and it can become cumbersome if the refresh token changes for every request done (*if* it changes, that's usually the case).
2. As you suggested the agent can keep the encryption password in memory. This option is also already implemented, but not done on default. When calling `oidc-add` to load an account configuration the agent never sees the encryption password, but only receives the de-crypted configuration. The `--pw-store` option can be used to let the agent store the encryption password so it can update the configuration file on disk. This is not implemented for the autoload feature of `oidc-token`.
3. Similar the `--pw-keyring` option could be used to store the encryption password in the systems' keyring. But I would recommend one of the other options.
4. The `--pw-env`, `--pw-cmd`, and `--pw-file` options can be used to pass the encryption password to `oidc-add` in another way than prompting the user for it. These options will also allow the agent to obtain the encryption password when needed (as long as it is still present in the env var / cmd / file).
5. The last option (and IMHO the best one) is to use gpg-agent for the encryption. This allows the loading of accounts without entering a password (if the used key is loaded in the gpg-agent) and it will also allow oidc-agent to update the account configuration. To use gpg encryption include the `--pw-gpg=KEY_ID` option in the `oidc-gen` call. For existing account configuration the encryption can be changed by calling `oidc-gen -u <short_name> --pw-gpg=<KEY_ID>`

**Comment by paulmillar** [comment]
Hi @zachmann ,

Thanks for the reply.  The issue isn't directly based on my own experiences, but rather triggered from the WLCG AuthZ discussion.

Your option 1. is certainly a good option for situations where the user is still present.  There is a risk of bombarding the user with such prompts, so it might be good if the prompt also included some hints on how to prevent subsequent prompts.

On option 2. perhaps it would make sense to make it a per-OP configuration option, rather than an option specified when running `oidc-add`.  My guess is the need for `--pw-store` will likely be tied to specific OPs.  Different OPs follow different policies, so this option likely makes sense for some OPs and not for others.

I should probably play with the `--pw-gpg` option, to learn more :-)

**Comment by zachmann** [comment]
> On option 2. perhaps it would make sense to make it a per-OP configuration option, rather than an option specified when running `oidc-add`. My guess is the need for `--pw-store` will likely be tied to specific OPs. Different OPs follow different policies, so this option likely makes sense for some OPs and not for others.

In principle I agree with you there. I think that this really makes sense. However, I know that for EGI it is possible to define per client if RTs are reused or not (at least with the current mitreid based implementation). So here it is not per OP, but rather per account configuration. I guess most users will only have one account config per OP anyway so that wouldn't be much of a difference in usability.

The big question here is how this can be configured and tracked. It would be easy with a config files, but we don't really use config files for such options, rather we rely on command line options.
Doing it per account configuration allows us to store the info in the account configuration file, but there is still the question how enable / disable it.

I already had the idea in the past that a configuration file for the agent and accounts would make some things easier.
So I want to think about that idea a bit more. 
I'll close this issue, since it is solved as it is. But open a new one for the per-OP / per-account setting.
