### ISSUE TITLE
oidc-token time flag without effect and always succssful 0 exit code even if no token got created

### ISSUE THREAD

**Issue by thdesy** [indigo-dc/oidc-agent#410]
Dear Developers,

when requesting a new ticket with/without the force flag a successful `0` exit code is always returned even if no new token got created.
Installed packages and OS look like [1]

E.g., requesting a token with a lifetime
```
oidc-token -f --time=7200 belle-desydebug-group > /tmp/token_$(id -u)
```
no error message is thrown and the exit code is `0`, which might be confusing in a manual approach and in a scripted environment such a case would not be noticed.

Also the `--time` seems to have no noticable effect. I.e., neither changing the lifetime to less or beyond 3600s has an effect and the resulting token has always a 1h lifetime, where the exit code is in all cases `0`

[1]
```
oidc-token 4.2.6

liboidc-agent4-4.2.6-1.el7.x86_64
oidc-agent-4.2.6-1.el7.x86_64
oidc-agent-cli-4.2.6-1.el7.x86_64
oidc-agent-desktop-4.2.6-1.el7.x86_64

on CentOS Linux release 7.9.2009 on 3.10.0-1160.53.1.el7.x86_64
```

[2]
```
grid@grid-mon0: [~] date
Thu Apr  7 17:30:41 CEST 2022
grid@grid-mon0: [~] oidc-token -f --time=7200 belle-desydebug-group > /tmp/token_$(id -u)
grid@grid-mon0: [~] cat  /tmp/token_$(id -u)  | cut -d. -f2 | base64 -d 2>/dev/null | jq
{
  "wlcg.ver": "1.0",
  "sub": "d73edcfa-61bc-42d4-bc42-aaf53a09fd82",
  "aud": "https://wlcg.cern.ch/jwt/v1/any",
  "nbf": 1649345446,
  "scope": "compute.write openid compute.create offline_access compute.read compute.cancel compute.modify wlcg wlcg.groups",
  "iss": "https://iam-belle.cloud.cnaf.infn.it/",
  "exp": 1649349046,
  "iat": 1649345446,
  "jti": "506bae10-5514-4e56-8b3f-9c319aa5469b",
  "client_id": "8d6cbce2-d46f-418b-9ed9-a1ba4c5e18b9"
}
grid@grid-mon0: [~] date -d @1649349046
Thu Apr  7 18:30:46 CEST 2022
grid@grid-mon0: [~] oidc-token -f --time=720 belle-desydebug-group > /tmp/token_$(id -u)
grid@grid-mon0: [~] echo $?
0
grid@grid-mon0: [~] date
Thu Apr  7 17:31:11 CEST 2022
grid@grid-mon0: [~] cat  /tmp/token_$(id -u)  | cut -d. -f2 | base64 -d 2>/dev/null | jq
{
  "wlcg.ver": "1.0",
  "sub": "d73edcfa-61bc-42d4-bc42-aaf53a09fd82",
  "aud": "https://wlcg.cern.ch/jwt/v1/any",
  "nbf": 1649345467,
  "scope": "compute.write openid compute.create offline_access compute.read compute.cancel compute.modify wlcg wlcg.groups",
  "iss": "https://iam-belle.cloud.cnaf.infn.it/",
  "exp": 1649349067,
  "iat": 1649345467,
  "jti": "82f3aed4-522f-4f0e-94a0-883875da25a4",
  "client_id": "8d6cbce2-d46f-418b-9ed9-a1ba4c5e18b9"
}
grid@grid-mon0: [~] date -d @1649349067
Thu Apr  7 18:31:07 CEST 2022
```

**Comment by zachmann** [comment]
Hi Thomas,

> when requesting a new ticket with/without the force flag a successful `0` exit code is always returned even if no new token got created. Installed packages and OS look like [1]

Including the `-f` flag should always return a new AT. Could you detail the situation where this is not the case?

> Also the `--time` seems to have no noticable effect. I.e., neither changing the lifetime to less or beyond 3600s has an effect and the resulting token has always a 1h lifetime, where the exit code is in all cases `0`

The `-t` option has a different semantic. This option is not meant to specify the lifetime of the requested AT (this is not defined in OIDC and not possible with any of the OPs I'm familiar with), instead it is the minimal lifetime, e.g. with `-t 1800` the returned AT will be valid for *at least* half an hour (but it could be more).

For wlcg iam (and many other OPs) the lifetime of an AT will always be 1hour. `oidc-agent` caches the AT it returns and will return the same AT if that satisfies the request (i.e. with the `-t` option it must be valid long enough). Therefore it is possible to receive an AT that has a remaining lifetime smaller than an hour. If the lifetime requested is greater than the currently cached AT has remaining a new AT is obtained from the OP and then returned. This token will have the maximum lifetime (1h).

It is true that requesting a lifetime greater than the maximum lifetime, does not return an error, but instead an AT with the maximum lifetime. This is the best we can do. I think that it is fine to not exit with an non-zero exit code here, because honestly there's nothing we or the user could change. Also this behavior is documented. Historically the easiest way to obtain a fresh AT was to specify `-t3600` (or greater) to force a new token. Now we have an explicit option for that (`-f`).
It does not make sense to combine the `-f` and `-t` option, since `-f` will already return a token with the maximum lifetime.

**Comment by thdesy** [comment]
OK - but it might be good to print a warning or so with the actual lifetime just in case the user does not check the token

**Comment by zachmann** [comment]
The actual lifetime of the AT (or more precisely the time when it will expire) can be obtained along with the token through different command line options. See https://indigo-dc.gitbook.io/oidc-agent/user/oidc-token/options#information-available-from-oidc-token for the different options, most relevant are `--all` and `--env`.
