### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [indigo-dc/oidc-agent#478]
Would you like to add more error handling for return values from functions like the following?
* [fprintf](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fprintf.html "Print formatted output") ⇒ [writeFile](https://github.com/indigo-dc/oidc-agent/blob/451f591fc0239fc2ca1cee0c65e413a09eae7440/src/utils/file_io/file_io.c#L158)
* [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [main](https://github.com/indigo-dc/oidc-agent/blob/451f591fc0239fc2ca1cee0c65e413a09eae7440/src/oidc-prompt/oidc_webview.c#L151)

**Comment by elfring** [comment]
:thought_balloon: I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by zachmann** [comment]
Your issue was weirdly phrased in the first place. You further comments emphasize this impression.
Looking at some of the other 100+ issues you opened around the same time with partly very similar content, I come to the conclusion that you are a bot that run a static code analyzer for many projects and reporting issues; might be combined with chatGPT.

We already use static code analyzer and don't need any more.

We will not add error handling for `printf` .

**Comment by elfring** [comment]
>…, I come to the conclusion that you are a bot …

It seems to be “convenient” somehow to think in such a direction.


>… and don't need any more.

:eyes: I got an other impression.


>We will not add error handling for `printf `.

:thought_balloon: It is just safer to [handle also “exceptional” situations](https://wiki.sei.cmu.edu/confluence/display/c/EXP12-C.+Do+not+ignore+values+returned+by+functions "Do not ignore values returned by functions"), isn't it?

**Comment by zachmann** [comment]
If you have any code suggestion we are always open for pull requests
