### ISSUE TITLE
Web server continues after client registration fails

### ISSUE THREAD

**Issue by paulmillar** [indigo-dc/oidc-agent#51]
I was using `oidc-gen -m` to register a client, but including the wrong redirection URL.

The web-server is started and the browser redirected to the OP.  The OP then fails the request because the redirection URL is not one of the registered redirection URL.

However, because the redirection URL is not accepted, the browser is NOT redirected back to the oidc-agent web-server (the one running on localhost).  The oidc-gen process shows a warning to indicate that something is going wrong.

Typing Control-C at this point terminates the oidc-gen process, but this does not kill the web-server.  Any subsequent attempt to register will then fail as the agent attempts to start a new web-server, only to discover that port is already occupied (by the orphaned web-server).

**Comment by zachmann** [comment]
When providing a redirect url to oidc-gen, multiple urls can be used so that oidc-agent is able to start the webserver on a different port if the first one is already in use.

However, we improved the shutdown behavior of the webserver (which is started by oidc-agent not oidc-gen). The webserver should now terminate as expected when oidc-gen is terminated by SIGINT and when too much polling tries were done.

**Comment by zachmann** [comment]
Changes included in v1.2.8
