### ISSUE TITLE
Autoregistered client should include host/node name

### ISSUE THREAD

**Issue by paulmillar** [indigo-dc/oidc-agent#54]
The `oidc-gen` command can auto-register the OIDC client within the OP.  The name of the client is something like: `oidc-agent:<ID>`  where `<ID>` is the short name for this identity.

It would be helpful if the client name included either the (simple) hostname, fqdn or some other identifier for the host on which oidc-agent is running.

The reason is that the same user may be oidc-agent running on multiple machines (a desktop and a laptop, for example).  It may be useful to distinguish between these two oidc-agent registrations.

**Comment by zachmann** [comment]
agent account configuration can be copied from one machine to another to enable usage on ceveral machines or to create the configuration on one machine and then move it another machine where this might not be possible (e.g. a server).

Therefore including the host name in the client name might not increase clarity. I suggest that if a user wants to distinguish he includes a identifier (e.g. host name) itself. This can be done in the short name, or - if that's not wanted because the same short name should be used on different machines with different configuration files - we can include an optional identifier field.

**Comment by zachmann** [comment]
Changes included in v1.2.8
